config/routes.rb
Blogcast::Application.routes.draw do
  root :to => "posts#index"

  resources :posts do
    resources :comments do
      collection do
        post :preview
      end
      member do
        delete :mark_as_spam
      end
    end
    
    resources :spams do
      collection do
        delete :incinerate
      end
      member do
        delete :mark_as_ham
      end
    end
  end
  
  resources :drafts
  
  match 'archives', :to => 'archives#index', :as => :archives, :via => [:get]
  
  match 'admin', :to => 'user_sessions#new', :as => :admin, :via => [:get]
  match 'logout', :to => 'user_sessions#destroy', :as => :logout, :via => [:delete]
  resource :user_sessions
  
  resources :users
  
  match 'sitemap', :to => 'sitemap#index', :via => [:get]
  
  match '*a', :to => 'errors#routing', :via => [:get]
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  validates_presence_of :title, :content
  
  attr_accessible :title, :content, :markdown, :author
  
  def to_param
    #1st: Removes all non alphanumeric characters from the string.
		#2nd: No more than one of the separator in a row.
		#3rd: Remove leading/trailing separator.
    "#{id}-#{title.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}"
  end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_filter :require_user
  
  # GET /drafts
  def index
     @drafts = Draft.all(:select => "title, id", :order => "created_at DESC")
  end
  
  # GET /drafts/1/edit
  def edit
    @draft = Draft.find(params[:id])
  end
  
  # PUT /drafts/1
  def update
    @draft = Draft.find(params[:id])

    #Save both HTML and Markdown
    @draft.title = params[:draft][:title]
    @draft.markdown = params[:draft][:markdown]
    @draft.content = BlueCloth.new(@draft.markdown).to_html
    
    if params[:save_draft]
      if @draft.save
        render :action => "edit", :notice => "Draft was successfully updated."
      else
        render :action => "edit", :notice => "Draft was not updated."
      end
    end
    
    if params[:save_post]
      @post = Post.new
      
      @post.title = @draft.title
      @post.markdown = @draft.markdown
      @post.content = @draft.content
      @post.author = @draft.author
      @post.commentable = true
      @post.posted_at = Time.now
      
      if @post.save
        @draft.destroy
        redirect_to(@post, :notice => 'Post was successfully created.')
      else
        render :action => "edit"
      end
    end
  end
  
  # DELETE /drafts/1
  def destroy
    @draft = Draft.find(params[:id])
    @draft.destroy

    redirect_to(drafts_url)
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/edit.html.erb
<% content_for :title do %> 
Edit Draft
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<% content_for :modstyles do %> 
<%= stylesheet_link_tag "modstyles" %>
<% end %>

<% content_for :modjs do %>
<%= javascript_include_tag "showdown" %>
<%= javascript_include_tag "wmd" %>
<%= javascript_include_tag "textarearesizer" %>
<%= javascript_include_tag "elastic" %>
<% end %>

<div class="post">
	
	<h2><%= link_to @draft.title, edit_draft_path, :class => "article" %>
	<span class="nobreak">
		<span class="author"><%= @draft.author %></span>
		<span class="date"><%= @draft.created_at.strftime("%b %d") %></span>
	</span>
	</h2>
	
	<p class="meta">
		<a href="#">Post a comment</a>
	</p>
		
	<div id="wmd-preview" class="entry"></div>
</div><!--post-->

<% content_for :sidebar do %> 
<div class="sidebar">
	<%= form_for(@draft) do |f| %>
	<div id="title-container" class="draft-title-container">
		<%= f.text_field :title %> 
		<p>/1234-title-me-wisely-brave-citizen</p>
	</div>
	
	<div id="wmd-container">
	<div id="wmd-button-bar"></div>

	<%= f.text_area :markdown, :id => "wmd-input", :cols => "92", :rows => "15" %>
	
	</div><!--wmd-container-->
	
	<ul class="options form-submit">
		<li><%= f.submit "Share your post with the world", :id => "post_submit", :name => "save_post", :confirm => "Are you sure you want to share this post with the world?" %></li>
		<li class="right"><%= f.submit "Update draft", :name => "save_draft" %></li>
	</ul>
	<% end %>
</div><!--sidebar-->

<% end %>

app/views/drafts/index.html.erb
<% content_for :title do %> 
Drafts
<% end %>

<% content_for :robots do %> 
<meta name="robots" content="noarchive"/>
<meta name="robots" content="noindex, nofollow"/>
<% end %>

<% content_for :modstyles do %> 
<%= stylesheet_link_tag "archives" %>
<% end %>

<% if @drafts.count == 0 %>

<div class="archives">
	<h2>No Drafts for Review</h2>
	<ul>
		<li>Write a post using the <%= link_to "Create Post", new_post_path %> option above.</li>
	</ul>
</div>

<% else %>

<div class="archives drafts">
	<h2>Drafts for Review</h2>
	<ul>
	<% for draft in @drafts %>
		<li><%= link_to draft.title, edit_draft_path(draft) %>
		
			<%= link_to draft_path(draft), :confirm => "Are you sure you want to delete this draft?", :method => :delete do %>
			<%= image_tag "delete.png", :alt => "delete draft", :title => "delete draft" %>
			<% end %>
		</li>
	<% end %>
	</ul>
</div>

<% end %>